Update test-britive.yaml

diff --git a/.github/workflows/test-britive.yaml b/.github/workflows/test-britive.yaml
--- a/.github/workflows/test-britive.yaml
+++ b/.github/workflows/test-britive.yaml
@@ -26,10 +26,11 @@ jobs:
         
     - name: Attempt Federated OIDC Login via GitHub
       run: |
-        echo "✅ Verifying login with pybritive..."
-        if pybritive checkout "widgeto-ci-deploy" --federation-provider github --mode print; then
+        run: |
+        echo "🔐 Attempting federated login to Britive using GitHub OIDC..."
+        if pybritive checkout "widgeto-ci-deploy" --federation-provider github --mode json; then
           echo "✅ Federated login successful."
         else
-        echo "❌ Federated login failed."
-        exit 1
+          echo "❌ Federated login failed."
+          exit 1
         fi
