Update test-britive.yaml

diff --git a/.github/workflows/test-britive.yaml b/.github/workflows/test-britive.yaml
--- a/.github/workflows/test-britive.yaml
+++ b/.github/workflows/test-britive.yaml
@@ -28,4 +28,4 @@ jobs:
     - name: Attempt Federated OIDC Login via GitHub
       run: |
         echo "🔐 Attempting federated login to Britive using GitHub OIDC..."
-        pybritive checkout "widgeto-ci-deploy" --federation-provider github --debug || echo "❌ pybritive checkout failed"
+        pybritive checkout "Widgeto-App-S3-Prod-Access" --federation-provider github --debug || echo "❌ pybritive checkout failed"
